apiVersion: v1
kind: Service
metadata:
  name: serviceregistry-api-service
spec:
  selector:
    app: serviceregistry-api-pod
  ports:
  - port: 8009
    nodePort: 30809
    protocol: TCP
    targetPort: 5016
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceregistry-api-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: serviceregistry-api-pod
  template:
    metadata:
      labels:
        app: serviceregistry-api-pod
    spec:
      containers:
      - name: serviceregistry-api-container
        image: serviceregistry-api:v1
        resources:
          limits:
            memory: "64Mi"
            cpu: "25m"
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: Production
        ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: serviceregistry-api-ingress
 annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: registry-api.trustmacus.com
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: serviceregistry-api-service
           port:
             number: 80